### ISSUE TITLE
px-datetime-field field miscalculates width in IE/Edge

### ISSUE THREAD

**Issue by joshsylvester** [PredixDev/px-datetime-field#10]
## Issue
It appears that as inputs are changed or as the user types into the px-datetime-field, the calculated inline width is incorrect when using browsers other than Chrome. Due to this miscalculation, the strings entered are not fully legible and are either cut off to the left or the right of the individual input field.

## Affected
This effects both Win/IE and Win/Firefox.

#### Mac Chrome (normal)
![px-datetime-mac-chrome](https://user-images.githubusercontent.com/30244294/50704496-6dd77700-100c-11e9-8229-eef0944307a9.png)
![px-datetime-mac-chrome-time](https://user-images.githubusercontent.com/30244294/50704497-6e700d80-100c-11e9-8acb-0482cf3177c2.png)

#### Win/Edge (not working as expected)
![px-datetime-win-edge](https://user-images.githubusercontent.com/30244294/50704510-7af46600-100c-11e9-9426-1fa407de7e4e.png)
![px-datetime-win-edge-time](https://user-images.githubusercontent.com/30244294/50704511-7af46600-100c-11e9-9af7-9151c4fa7dcf.png)

#### Win/Firefox has similar problems, but not at the same time.
![px-datetime-win-firefox-default](https://user-images.githubusercontent.com/30244294/50704768-5947ae80-100d-11e9-8f76-1ea6811d5bc6.png)
![px-datetime-win-firefox-mmddyyyy](https://user-images.githubusercontent.com/30244294/50704769-5947ae80-100d-11e9-9c38-c69ae8fc1f8f.png)
![px-datetime-win-firefox-time](https://user-images.githubusercontent.com/30244294/50704770-5947ae80-100d-11e9-99ed-71fb117b8ac3.png)

**Comment by arongraham-ge** [comment]
@joshsylvester commit looks ready for merge. are you able to do this or would you like me to?
