### ISSUE TITLE
Test not able to get into method that fires 'px-datetime-submitted'

### ISSUE THREAD

**Issue by talimarcus** [PredixDev/px-datetime-field#3]
Failing test: submit without buttons » event is fired when changing valid value

The test is not getting into the method that fires the event 'px-datetime-submitted'. The method that fires this event is _notifyDateTimeChanged (in px-datetime-behavior.html). The event is being fired when you run the code.

For now, we have commented out the one line that is failing the test: 

```
assert.equal(i, 1);
```

The failing test:
```
  test('event is fired when changing valid value', function(done) {
      var entries = Polymer.dom(field.root).querySelectorAll('px-datetime-entry'),
          dateCells = Polymer.dom(entries[0].root).querySelectorAll('px-datetime-entry-cell'),
          wrapper = Polymer.dom(field.root).querySelector('#fieldWrapper'),
          i = 0;

      var listener = function(evt) {
        i++;
        //make sure string has been kept in sync
        assert.equal(field.momentObj.toISOString(), field.dateTime);
      };

      field.addEventListener('px-datetime-submitted', listener);

      //valid month, should trigger event
      fireKeyboardEvent(dateCells[1], '0');
      fireKeyboardEvent(dateCells[1], '3');

      setTimeout(function() {
        //figure out why this is causing the test to fail
        // assert.equal(i, 1);

        //validation failed should have been removed
        assert.isFalse(wrapper.classList.contains('validation-failed'));
        field.removeEventListener('px-datetime-submitted', listener);
        done();
      }, 100);
    });
```

**Comment by benoitjchevalier** [comment]
Let's recheck this, I think the test is genuinely failing because the component is actually broken: https://github.com/PredixDev/px-datetime-picker/issues/16

**Comment by nonmetalhail** [comment]
Interesting, because we were seeing it work in the demo and the it worked in the other tests, just not this one

**Comment by benoitjchevalier** [comment]
Haven't tried it myself, just remembered this issue someone opened this morning. Seemed oddly related

**Comment by nonmetalhail** [comment]
I agree. Just scared it is some very strange edge case under which it fails...

**Comment by nonmetalhail** [comment]
Actually, [PredixDev/px-datetime-picker/pull/17](https://github.com/PredixDev/px-datetime-picker/pull/17) claims to fix that bug and would be unrelated to this issue.

**Comment by mdwragg** [comment]
Agreed that we need to check that this isn't _actually_ broken... Failing tests are usually a good sign of badness ;-)
