### ISSUE TITLE
Version 2.0.4 is not available on bower

### ISSUE THREAD

**Issue by shinxi** [PredixDev/px-datetime-field#6]
@davidrleonard @katemenkhaus Just saw [some fix](https://github.com/PredixDev/px-datetime-field/commit/b96246c181bc520320c0ebf6fe1aa316a455f0df#diff-f733f6b36730b199b8d163ff5cf1c141) for px-datetime-field at 2.0.4, but we can't upgrade to the version 2.0.4, see below.
![image](https://user-images.githubusercontent.com/1262296/34809205-8c6ec392-f6ce-11e7-91cc-29ca7e341e7a.png)
Any idea? We need the fix so that our [React Wrapper using refs](https://github.com/PredixDev/px-calendar-picker/issues/14#issuecomment-353161912) can work as expected when it is lazy rendered.

See [code sample](https://codesandbox.io/s/1ow02wvv64) at sandbox.

Thanks in advance.

**Comment by katemenkhaus** [comment]
Hi @shinxi, 
I apparently didn't tag the changes. That has been fixed and v2.0.4 is now available on bower. 
Thanks, 
Kate

**Comment by mdwragg** [comment]
💯
