### ISSUE TITLE
Timezone UTC dropdown: Update from "string" order to numerical order

### ISSUE THREAD

**Issue by andrealperry** [PredixDev/px-datetime-field#9]
The Etc/GMT+“X” dropdown numbers are not sorted/listed in numerical order - e.g., 1, 10, 11, 12, 2. Seems to be listed in “string” order, might just be the default of the dropdown or how the list was built?

**Screenshot:**
**![screen** shot 2018-03-09 at 4 45 05 pm](https://user-images.githubusercontent.com/30873778/37309662-d36e58ac-25fe-11e8-8185-0217b3977492.png)

**Comment by randyaskin** [comment]
Fixed in latest datetime-common to order the timezones in order from -14 to +12 instead. Should be picked up by all components on next rebuild.
